permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Name
        id: tag
        run: echo "NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build go
        run: |
          go mod download
          for os in linux; do
            for arch in amd64 arm64; do
              echo -e "$os $arch\n"
              GOOS=$os GOARCH=$arch go build -o fife-$GOOS-$arch
            done
          done
      - name: Get last version
        id: last
        run: echo "VERSION=$(git tag --list "v[0-9]*.[0-9]*.[0-9]*" --sort=-version:refname | head -n 2 | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Build release file
        run: git log $LAST_VERSION..HEAD --pretty=format:"- %s (%h)" > release.md
        env:
          LAST_VERSION: ${{ steps.last.VERSION }}
      - name: Create release
        run: gh release create $TAG -F release.md ./fife-*
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ steps.tag.outputs.NAME }}
        